#!/bin/zsh

# Checks if we have a argument
if [ $# -eq 0 ]; then
  branch=$(git branch | fzf --print0 --height 40% --border | tr -d '* ')
  git checkout $branch
  exit 0
fi
# if we do we just pass all the arguments (but the first) to the default git checkout
git checkout $@
