#!/bin/zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(tmux ls | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

echo $selected | awk -F: '{print $1}' | xargs tmux kill-session -t
